name: Build EPUB and PDF

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Install Pandoc and PDF tools
        run: sudo apt-get install pandoc texlive-xetex -y

      - name: Generate EPUB and PDF
        run: |
          mkdir -p build
          pandoc docs/*.md -o build/AlpineCohabitat.epub --metadata-file=docs/metadata.yaml --toc --toc-depth=2
          pandoc docs/*.md -o build/AlpineCohabitat.pdf --metadata-file=docs/metadata.yaml --toc --toc-depth=2

      - name: Commit and push output
        run: |
          git pull origin main
          git add build/AlpineCohabitat.*
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto-update EPUB and PDF on commit"
            git push origin main
          fi
